print ("Please enter the following information:")
namelast = input("Last Name: ").upper()
namefirst = input("First Name: ").capitalize()
jobtitle = input ("Job Title: ").title()
identification = input ("id number: ")
email = input ("Email adress: ").lower()
phonenumber = input ("Phone number: ")
#Extra Info vvv
hair = input ("Hair color: ").capitalize()
eye = input ("Eye color: ").capitalize()
month = input ("Starting month: ").capitalize()
print ("Training Completed?")
training = input ("Yes/No ").capitalize()
print ("")
#Compact output in one line of code vvv
print (f"The ID Card is:\n-------------------------\n{namelast}, {namefirst}\n{jobtitle}\nID: {identification}\n\n{email}\n{phonenumber}\n\nHair: {hair:15}\t\tEyes: {eye}\nMonth: {month:14}\tTraining: {training}\n-------------------------")